on:
  push:
    branches:
      - main 
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          pull-request-title-pattern: "[skip ci] chore ${scope} release${component} ${version}"

